name: Deploy to Google Apps Script

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install clasp
      run: npm install -g @google/clasp

    - name: Authenticate clasp

      env:
        CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}
      run: |
        echo "$CLASP_CREDENTIALS" > ./credentials.json
        clasp login --creds ./credentials.json

    - name: Set up clasp project
      run: clasp clone ${{ secrets.SCRIPT_ID }}

    - name: Push to Google Apps Script
      run: clasp push

    - name: Deploy Google Apps Script

      run: clasp deploy