name: Deploy to Google Apps Script

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install clasp
      run: npm install -g @google/clasp

    - name: Authenticate clasp
      run: |
        echo "${{ secrets.CLASP_CREDENTIALS }}" > ~/.clasprc.json

    - name: Set up clasp project
      run: |
        clasp clone ${{ secrets.SCRIPT_ID }} || echo "Project already cloned."

    - name: Push to Google Apps Script
      run: clasp push

    - name: Deploy Google Apps Script
      run: clasp deploy
